name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Gettext
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gettext
          version: 1.0
          execute_install_scripts: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
