name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  EXTENSION_NAME: flickernaut@imoize.github.io.shell-extension

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Compile schemas
        run: glib-compile-schemas schemas

      - name: Copy Files to dist
        run: |
          cp metadata.json dist/
          cp -r nautilus-extension/* dist/
          cp -r schemas dist/

      - name: Archive Package
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./dist
          format: zip
          includeRoot: false
          destfilename: '${{ env.EXTENSION_NAME }}'
          dest: ./artifacts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: ${{ env.EXTENSION_NAME }}
          compression-level: 9

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./artifacts/${{ env.EXTENSION_NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body: Initial Release
