name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  EXTENSION_NAME: flickernaut@imoize.github.io.shell-extension

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gettext
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gettext
          version: 1.0
          execute_install_scripts: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: ${{ env.EXTENSION_NAME }}
          compression-level: 9

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: true
          useGitmojis: false

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.EXTENSION_NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
